album/urls.py
from django.urls import path

from .views import (
    oneAlbumView,
    allAlbumsView,
    albumSearchView
)

app_name = 'album'
urlpatterns = [
    path('search/',albumSearchView,name="search"),
    path('',allAlbumsView,name='allAlbums'),
    path('<slug:slug>/',oneAlbumView,name='oneAlbum')
]

jkphoto/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    homeView,
    aboutView
)
from django.contrib.sitemaps.views import sitemap
from .sitemaps import staticViewSitemap
from album.sitemaps import albumSiteMap
from subscriber.sitemaps import subscriberSiteMap

sitemaps = {
    'static': staticViewSitemap,
    'albums': albumSiteMap,
    'subscribe': subscriberSiteMap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homeView,name='home'),
    path('about/',aboutView,name='about'),
    path('albums/',include('album.urls')),
    path('',include('subscriber.urls')),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},
    name="django.contrib.sitemaps.views.sitemap")
]

album/models.py
from django.db import models
from django.db.models.signals import post_save
from django.utils.formats import date_format
from django.utils import timezone
from django.urls import reverse
from .utils import slugfiy

'''
*****GLOSSARY*****

-title:         the title of the article that the user will see, also 
                used for slug generation
-content:       captions that will go under the album in a post, there
                will be one caption per post, not one per image in an
                album. This is optional.
-timeCreated:   time stamp of when object was created or saved. This 
                is uneditable.
-updated:       time stamp of last time the object was saved. This is
                uneditable.
-publish:       a boolean checkbox. When set to True, the album will
                be posted to the site for all to see and the date at 
                this time will be appended to the slug. When set to
                fasle the post will be hidden from the site.
-publishDate:   the date in which the post was published. This date can
                be set independently from the publish blooean. 
-slug:          this will be unique to every post and autogenerated
                upon creation of an object. When an object is published
                the publish date will be appended to the slug. Slugs 
                appear in the browser url. If posts are somehow not 
                unique and number is appeneded to the slug to differ 
                between these posts. 

'''

# Create your models here.
class album(models.Model):
    title = models.CharField(max_length=75)
    content = models.TextField(null=True,blank=True)
    timeCreated = models.DateTimeField(auto_now_add=True,editable=False) 
    updated = models.DateTimeField(auto_now=True,editable=False)
    publish = models.BooleanField(null=True,blank=True,default=False)
    publishDate = models.DateField(null=True,blank=True,default=None)
    slug = models.SlugField(null=True,editable=False)
    postType = models.CharField(max_length=75,null=True,default=None,blank=True,
                            choices=[("observations","observations"),
                                    ("portraits","portraits"),
                                    ("landscapes","landscapes"),
                                    ("bmx","bmx"),
                                    ("family","family")])

    # Getters
    def getTitle(self):
        return self.title
    def getContent(self):
        return self.content
    def getTimeCreated(self):
        return self.timeCreated
    def getUpdated(self):
        return self.updated
    def getPublish(self):
        return self.publish
    def getPublishDate(self):
        return self.publishDate
    def getSlug(self):
        return self.slug
    # IMPORTANT: get url for links to render view
    def getAbsoluteUrl(self):
        return reverse('album:oneAlbum',kwargs={'slug': self.slug})
    
    # Setters
    def setUpdated(self):
        album.objects.filter(id=self.id).update(updated=timezone.now())
    # Set slug with title only, does not include publish date
    def setSlug(self):
        titleSlug = slugfiy(self.title)
        album.objects.filter(id=self.id).update(slug=titleSlug)
    # Set slug with publish date
    def setSlugPublish(self):
        ddmmyyyy = date_format(self.publishDate,'d-m-Y')
        titleSlug = slugfiy(self.title)
        publishSlug = f'{titleSlug}-{ddmmyyyy}'
        album.objects.filter(id=self.id).update(slug=publishSlug)

    '''
    Override save function to note any changes in the fields of a 
    given object before and after it is saved by the user in the 
    django admin so that some automated proecesses can be carried out.
    An example of that is slug generation after initial save and 
    appending the publish date to the slug upon switching the boolean
    publish to True.
    '''
    def save(self,*args,**kwargs):
        try:
            old = album.objects.get(pk=self.pk)
            new = self
            updatedFields = []
            for field in album._meta.get_fields():
                fieldName = field.name
                try:
                    if getattr(old,fieldName) != getattr(new,fieldName):
                        updatedFields.append(fieldName) 
                except Exception as ex:
                    pass
            kwargs["update_fields"] = updatedFields
        except:
            pass
        return super().save(*args,**kwargs)
    
"""
The Simple Image Class that will hold photos in the album.
"""
class albumImage(models.Model):
    album = models.ForeignKey(album,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/album/')

def albumPostSave(instance, created, *args, **kwargs):
    if created or kwargs["update_fields"] != []:
        instance.setSlug()
    if instance.publish == True:
        instance.setSlugPublish()
    else:
        instance.setSlug()
    instance.setUpdated()

# Connect the post-save signal to the overridden save function
post_save.connect(albumPostSave,sender=album)

templates/about.html
{%extends "base.html"%}
{%block content%}

<!-- Load Static -->
{% load static %}

<!-- Load CSS -->
<link rel="stylesheet" href="{% static 'css/stylesAbout.css' %}">


<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-12 col-lg-8">
            <h3>
                About
            </h3>
            <p>
                Justin Koebele is a photographer based out of Long Island, NY. Primarily shooting on film, his goal is to document his life and interests through photography. His hobbies include BMX, skateboarding, music, traveling, and more.
            </p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-10 col-lg-8">
            <img src="{% static 'images/justin-about-photo-3.jpg'%}" alt="Image of Justin">
        </div>
    </div>
</div>

<div id="contact" class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-12 col-lg-8">
            <h3>
                Contact
            </h3>
            <p>
                justinkoebelephoto@gmail.com
            </p>
        </div>
    </div>
</div>


{%endblock content%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JK Photo</title>

    <!-- BOOTSTRAP v5 -->
    <!-- Load the tag library -->
    {% load bootstrap5 %}
    <!-- Load CSS and JavaScript -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- Load Static -->
    {% load static %}

    <!-- Load CSS -->
    <link rel="stylesheet" href="{% static 'css/stylesBase.css' %}">

    <!-- Load favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >

    <!-- Preview Info -->
    <meta property="og:title" content="Justin Koebele Photo">
    <meta name="description" content="A collection of photos.">
    <meta property="og:description" content="A collection of photos.">
    <!-- <meta property="og:image" content="{% static 'images/PagePreview.png'%}"> -->


    <!-- Mobile home screen icons -->
    <link rel="apple-touch-icon" href="{% static 'images/favicon.png' %}">
    <link rel="icon" href="{% static 'images/favicon.png' %}">
</head>

<body class="d-flex flex-column min-vh-100 h-100">
    <!-- NAV BAR -->
    <nav class="navbar navbar-expand-lg shadow">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <img src="{% static 'images/header-icon-2.png' %}" width="50" height="50" alt="navbar-logo"/>
            Justin Koebele Photo
          </a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>


        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/albums/">Photos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/about/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/about/#contact">Contact</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/subscribe/">Subscribe</a>
              </li>
            </ul>

            <a href="https://www.buymeacoffee.com/justinkoebele" class="nav-link ps-0 pe-1">
              <img src="{% static 'images/bmc-button.svg' %}" height="42" alt="bmc-logo">
            </a>

            <form action='/albums/search/' method="GET" class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search All Albums" name="q" aria-label="Search">
              <button class="btn btn-light" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      {%block content%}
      {%endblock content%}

      <!-- STICKY FOOTER -->
      <footer class="footer py-3">
        <div class="container-fluid text-white">
          <ul class="footer-links">
            <li class="footer-item py-1">
              <a href="/">Home</a>
            </li>
            <li class="footer-item py-1">
              <a href="/albums/">Photos</a>
            </li>
            <li class="footer-item py-1">
              <a href="/about/">About</a>
            </li>
            <li class="footer-item py-1">
              <a href="/about/#contact">Contact</a>
            </li>
            <li class="footer-item py-1">
              <a href="/subscribe/">Subscribe</a>
            </li>
            <li class="footer-item py-1">
              <a href="/unsubscribe/">Unsubscribe</a>
            </li>
            <li class="footer-item py-1">
              <a href="https://www.buymeacoffee.com/justinkoebele">Buy Me A Coffee</a>
            </li>
            <li class="footer-item py-1">
              <a href="https://github.com/freddydrew/JKPhoto">GitHub</a>
            </li>
            <hr>
            <li class="footer-item">
              <span >Copyright DERFWERD © 2024, All Rights Reserved</span>
            </li>
          </ul>
        </div>
      </footer>

</body>
</html>

templates/home.html
{%extends "base.html"%}
{%block content%}
{% load static %}
<!-- Load CSS -->
<link rel="stylesheet" href="{% static 'css/stylesHome.css' %}">

<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-12 col-m-8 col-lg-8">
            <div class="card justify-content-center align-items-center" id="subscribe-card">

                <h2 class="mt-5">
                    GET THE NEWSLETTER
                </h2>
                <p class="mx-3" align="center">
                    Please submit your email address to receive the monthly photo newsletter.
                </p>

                <form method="POST" class="justify-content-center align-items-center d-flex">
                    <!-- need this token every time in django for POST-->
                    {%csrf_token%}
    
                    {%for field in form%}
                        <div class="subscribe mx-2 mt-2 mb-5">
                            {%if field.errors%}
                                <div class="alert alert-danger">
                                    {{ field.errors | striptags}}
                                </div>
                                <input id="{{field.id_for_label}}" name="{{field.name}}" 
                                type="text" placeholder="{{field.help_text}}" 
                                class="form-control form-control-lg">
                                
                            {%else%}
                                <input id="{{field.id_for_label}}" name="{{field.name}}" 
                                type="text"
                                placeholder="{{field.help_text}}"
                                class="form-control form-control-lg">
                            {%endif%}
                        </div>
                    {%endfor%}

                    <button type="submit" class="btn btn-outline-dark btn-lg mx-2 mt-2 mb-5 subscribe">
                        SUBSCRIBE
                    </button> 

                    {%if robotForm.recaptcha.errors%}
                        <div align="center" class="mb-4">
                            <small>
                                <strong class="text-danger">
                                    Are you a robot!?  
                                </strong>
                                reCAPTCHA has decided you are. Wait and try agian.
                            </small>
                        </div>
                        {{robotForm.recaptcha}}
                    {%else%}
                        {{robotForm.recaptcha}}
                    {%endif%}

                </form>
    
                
                {%if status == True%}
                    <div class="alert alert-success" role="alert">
                        Success!
                    </div>
                {%elif status == False%}
                    <div class="alert alert-danger" role="alert">
                        You are already subscribed or this email is not valid!
                    </div>
                {%endif%}
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-12 col-m-8 col-lg-8">
            <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">

                 <!-- Inner -->
                 <div class="carousel-inner">
                    {%for obj in sliderObjList%}
                        {%if forloop.counter0 == 0%}
                            <!-- Active item -->
                            <div class="carousel-item active" data-bs-interval="3000">
                                <a href="{{obj.getAbsoluteUrl}}" style="text-decoration: none;">
                                    <img src="{{obj.albumimage_set.all.0.image.url}}" class="mx-auto d-block" alt=""/>
                                    
                                </a>
                            </div>

                        {%else%}
                            <!-- Item -->
                            <div class="carousel-item" data-bs-interval="3000">
                                <a href="{{obj.getAbsoluteUrl}}" style="text-decoration: none;">
                                    <img src="{{obj.albumimage_set.all.0.image.url}}" class="mx-auto d-block" alt=""/>
                                </a>
                            </div>
                        {%endif%}
                    {%endfor%}      
                </div>
                <!-- Inner -->

                <!-- Carousel Controls, left and right arros -->
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
                <!-- Carousel Controls, left and right arros -->

              </div>
        </div>
    </div>
</div>

{%endblock content%}